name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - with:
        node-version: '10.x'
    - name: Get npm i for dx-scanner
      run: npm i -g dx-scanner
    - name: Run a dx-scanner
      run: dx-scanner
    - name: dx-scanner done
      run: |
        echo Finished,
